In [ ]:
!pip install feature-engine

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting feature-engine
  Downloading feature_engine-1.6.0-py2.py3-none-any.whl (319 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.4/319.4 KB 5.6 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from feature-engine) (1.2.2)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.9/dist-packages (from feature-engine) (0.13.5)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.9/dist-packages (from feature-engine) (1.22.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.9/dist-packages (from feature-engine) (1.10.1)
Requirement already satisfied: pandas>=1.0.3 in /usr/local/lib/python3.9/dist-packages (from feature-engine) (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.3->feature-engine) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.3->feature-engine) (2022.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.0.0->feature-engine) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=1.0.0->feature-engine) (1.1.1)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.9/dist-packages (from statsmodels>=0.11.1->feature-engine) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.9/dist-packages (from statsmodels>=0.11.1->feature-engine) (23.0)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from patsy>=0.5.2->statsmodels>=0.11.1->feature-engine) (1.16.0)
Installing collected packages: feature-engine
Successfully installed feature-engine-1.6.0

In [13]:
#import library
import pandas as pd
import joblib
import sklearn
import numpy as np

In [7]:
# Load The Models
with open('full_pipeline.pkl', 'rb') as file_1:
  model_pipeline = joblib.load(file_1)

from tensorflow.keras.models import load_model
model_ann = load_model('model_func_tune.h5')

In [3]:
#Dataframe random
data = {'membership_category' : ['Gold Membership','Silver Membership','Premium Membership','No Membership','Gold Membership'],
        'feedback' : ['Too many ads','Poor Product Quality','Poor Customer Service','Poor Product Quality','Poor Website'],
        'points_in_wallet' : [711.990000,797.200000,794.980000,237.815232,0.000000],
        'avg_transaction_value'	: [44807.63,1212.51,25339.98,29623.97,16873.33]}

In [4]:
inf = pd.DataFrame(data,columns=data.keys())
inf

,membership_category,feedback,points_in_wallet,avg_transaction_value
0,Gold Membership,Too many ads,711.990000,44807.63
1,Silver Membership,Poor Product Quality,797.200000,1212.51
2,Premium Membership,Poor Customer Service,794.980000,25339.98
3,No Membership,Poor Product Quality,237.815232,29623.97
4,Gold Membership,Poor Website,0.000000,16873.33

In [9]:
full_pipeline = model_pipeline.transform(inf[['membership_category','feedback','points_in_wallet','avg_transaction_value']])
full_pipeline

array([[0.53500777, 0.44400743, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 3.        ],
       [0.60189895, 0.00415735, 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 2.        ],
       [0.60015622, 0.24758986, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 4.        ],
       [0.16277317, 0.29081289, 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.16216616, 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 3.        ]])

In [10]:
inf_final = full_pipeline.copy()

In [14]:
y_pred_inf = model_ann.predict(inf_final)
y_pred_inf = np.where(y_pred_inf >= 0.5, 1, 0)
y_pred_inf

1/1 [==============================] - 0s 29ms/step

array([[0],
       [0],
       [0],
       [1],
       [0]])

In [15]:
df_pred_model = pd.DataFrame(y_pred_inf, columns=['Pred_Churn']) 
df_pred_model

   Pred_Churn
0           0
1           0
2           0
3           1
4           0

In [16]:
df_combined = pd.concat([inf, df_pred_model], axis=1)
df_combined

,membership_category,feedback,points_in_wallet,avg_transaction_value,Pred_Churn
0,Gold Membership,Too many ads,711.990000,44807.63,0
1,Silver Membership,Poor Product Quality,797.200000,1212.51,0
2,Premium Membership,Poor Customer Service,794.980000,25339.98,0
3,No Membership,Poor Product Quality,237.815232,29623.97,1
4,Gold Membership,Poor Website,0.000000,16873.33,0

Berikut adalah hasil prediksi dari load model pada model saving yang telah di lakukan